### ISSUE TITLE
Install Settings for Synology nas

### ISSUE THREAD

**Issue by sp8ced21** [Jalle19/xbmc-video-server#165]
Hey sam, ive finally got install instructions wriiten up, feel free to add them to your resource, i have manged to hone it down to instalation similar to unbunto with ability to update without having to use windows install to get in on syno nas.

Installation
Synology DSm 5.0 or Higher

Anyone following these instructions do so at your own risk, these are here a ref guide to help get this running on synology Nas.

This section contains instructions on how to install this application Synology DSm 5.0 or higher. If you're using another version of the above or a different distribution altogether you'll eventually have to adapt them slightly. The instructions assume that your shell user.
to install this you will need PUTTY and for some things you can use WinSCP instead (will give you file view)
When using Putty or WinSCP or similar programme remember username is "root" and the password is your synology admin password.

Before you begin you must complete the following setups before the server files can be installed.

Ensure SSH is enabled this can be done via - Control Panel>>>Terminal & SNMP tick "ENABLE SSH"

1. Enable Web station - Controll Panel>>Web Services (there are two tabs at top web services and php make sure it selected on web services)
Tick ENABLE Web Station (will create folder in shared folders called "WEB"
Click "Virtual Host" under "Enable Web Station" click Create
Set "sub folder" as xbmc-video-server
Set "Hostname" as http://yourddns.example.com
Set "Port" default is 80 ( if you wish to use a different port see below step)
To have a different port enable "HTTP Service" tick "Add additional Port" and enter your prefered port number.

2. Staying in Same menu the tab at top will say "PHP Settings" select this
Ensure "Enable Cache" is ticks
Ensure "Customize PHP open_basdir" is ticked
underneath this you will see a box which will have the following or similar

    :/etc.defaults:/etc:/usr/syno/synoman:/tmp:/var/services/tmp:/var/services/web:/var/services/homes

click on this go to the end and paste in the following with no spaces

    :/dev/urandom:/root/.composer/.htaccess:/root:/usr/bin

Once done above click APPLY to save the changes.

3. Ussing Putty SSH - enter the below command

    vi /etc/php/conf.d/extentions.ini

#find line ;extension = phar.so, then remove ";" then save it

(you can use WinSCP to manually navigate to this file drag it to your desktop open in word pad edit as above save and paste it back to replace original file)

Synology DSm 5.0

Run the following commands, one by one, in the exact order shown here:
(Volume - is whatever your shared volume is called in this example its volume 1)

    cd /volume1/web
    git clone git://github.com/Jalle19/xbmc-video-server.git
    cd xbmc-video-server
    curl -sS https://getcomposer.org/installer | php
    mv composer.phar /usr/bin/composer
    php composer.phar install
    ./src/protected/yiic createinitialdatabase
    ./src/protected/yiic setpermissions

Finally, after saving the file you must restart Apache either go into Synology Web Gui and select restart or via ssh "httpd -k restart" (ive found ssh way to be hit or miss)
Update via SSH in Putty
To update your copy of the software to the latest version, run the following commands via SSH direct after loging in with user "root"

git pull
php composer.phar install
./src/protected/yiic migrate --interactive=0

Once done this will give you up and running xbmc-video-server on synology, most encoutered errors are usually file permission issue so make sure you have correct file permision set for your Web folder.

This will allow for update using SSH

**Comment by Jalle19** [comment]
Closing this since it's way too complicated for a normal user to do this, what really should be done is a native synology package (see http://global.download.synology.com/download/Document/DeveloperGuide/DSM_Developer_Guide.pdf). I don't have a Synology NAS so I'm not particularly interested in doing the work myself.
