### ISSUE TITLE
Movies Details Pages - ADD a custom field (information)

### ISSUE THREAD

**Issue by Galixte** [Jalle19/xbmc-video-server#181]
Hi,

as I mentioned it here : https://github.com/Jalle19/xbmc-video-server/pull/74

Is it possible to add a custom field (information) on each movies details pages ? (Only admin users can be edit this field).

Like this system of a custom title on the header : https://github.com/Jalle19/xbmc-video-server/issues/174

This could solve my problem of information on the quality of the source of my films to display the source quality (SCREENER/CAM/TS/TC/WP/DVDSCR/R3/R4/R5/R6/WEBDL/WEBRIP...) because my movies files don't have any information just the movie title.

I use http://www.tinymediamanager.org before to make available my medias files in XBMC.

**Comment by Jalle19** [comment]
Closing this for now, please open a new issue if you ever get around to creating those custom icons.

**Comment by Galixte** [comment]
Ok Sir. i will soon. ;)

**Comment by Galixte** [comment]
New PR, here: https://github.com/Jalle19/xbmc-video-server/pull/257
