### ISSUE TITLE
Issue on "php composer.phar install"

### ISSUE THREAD

**Issue by zipeldiablo** [Jalle19/xbmc-video-server#219]
Hi, i got an issue when i try to run your installation instructions on my docker container.
It returns me this : 
Step 18 : RUN php composer.phar install
 ---> Running in ee33a5140b7b
Composer could not find a composer.json file in /
To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section

Wich i find weird considering the composer.json is at the root of the directory T_T
Any idea to solve this?

**Comment by Jalle19** [comment]
Since this seems to be a Docker-specific issue I'm going to close this. I'm sorry I can't help you any further, like I said I've never used Docker.
