### ISSUE TITLE
Stream with Kodi

### ISSUE THREAD

**Issue by iamnomad** [Jalle19/xbmc-video-server#224]
Hi Jalle19,

Does this setup can be implement with kodi?

**Comment by Jalle19** [comment]
Yes, it works with Kodi too despite the name.

**Comment by iamnomad** [comment]
1) Ok successfully setup xbmc video server but cannot play. I'm getting this error 

HTTP load failed with status 401. Load of media resource http://stream.localhost/xbmc-nomad/%2fmedia%2fmimz%2fSTORAGE1%2fMovies%2fDragonheart%203%20The%20Sorcerer%27s%20Curse%20(2015)20%5b1080p5d%2fDragonheart.3.The.Sorcerers.Curse.2015.1080p.BluRay.x264.YIFY.mp4 failed.

2) However if i did not configure backend i will receive this error
"All candidate resources failed to load. Media load paused."

3) The strangers thing is i've change xbmc password and i've already configured it to my .conf file, when i hover mouse on download link it will still show my old password which will resulting below error if i click on download link.

Server not found
Firefox can't find the server at k.
    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer's network connection. If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

I'm using Ubuntu 14.10
Kodi 14.2

**Comment by iamnomad** [comment]
Hi,

Finally i've sort it out the reason of error HTTP load failed with status 401. The reason for this error it's sorts like permission error. I've wrongly configured/add my movie library. Do not directly set content of your movie folder directly from storage.

This is what it should be done to add Movie library
1. Go to kodi setting>file manager > add source >path to my Movie folder
2. Click video > files > Add video > path to my Movie folder.
