### ISSUE TITLE
Integrate xmbc-video-server as Owncloud app into Owncloud server

### ISSUE THREAD

**Issue by godfuture** [Jalle19/xbmc-video-server#228]
Kodi is really good in scraping and managing the multi media. Owncloud is good at sharing. Together it would be awesome to have Kodi providing media info for Owncloud.
As there is already an addon for Kodi to access Owncloud, this issue aims in making better use of both strengths. Even if Kodi is some kind of standalone, its not a server yet, I know. But I am already using it as 24/7 application on my server. It works!

I would love to access my movies, series and music over Owncloud. Do you think this has a change? I guess xbmc-video-server is written in php & java script, too?!

**Comment by Jalle19** [comment]
While it sounds like a nice thing to have it is definitely out of the scope for this project. I am not even sure where to begin if you'd want to integrate the library into Owncloud.

If you want to share your library with friends or have access to it on the field this application is designed to do just that.
