### ISSUE TITLE
error 400 on Movie and tv show

### ISSUE THREAD

**Issue by deckos** [Jalle19/xbmc-video-server#230]
Hi , I just finished installing XBMC -video- server raspbmc ( Raspberry Pi + kodi distri ) . everything looks good , I was able to configure the backend, but then I have error 400 on Movies and TV shows pages. An idea?
thanks

**Comment by sigboe** [comment]
There are no official Kodi distro on RPi, so please specify witch one you are using?
Have you enabled .htaccess in apache?
What php version are you running? 
Can you post a pastebin of your apache default sites file? (the location and name of this file is dependent on what distro you are using)
Did you run composer.php with a user that has write access to the xbmc-video-server folder?

**Comment by Jalle19** [comment]
If you can access the application log, please look there for any red lines and post the full snippets here.

**Comment by deckos** [comment]
I'm using the "old" raspbmc it's based on debian -> http://www.raspbmc.com/index.html
I followed the instrucion on the wiki page so I guess I'm using php5
here is my /etc/apache2/sites-available/default file -> http://pastebin.com/c0zpa1k4
and the application log file -> http://pastebin.com/AyY1ME7T
thanks

**Comment by Jalle19** [comment]
Please see https://github.com/Jalle19/xbmc-video-server/wiki/Installation-instructions-%28Linux%29#updating-on-linux for how to upgrade.

**Comment by deckos** [comment]
thanks! everything works, but unfortunately it's very slow on a Rpi

**Comment by Jalle19** [comment]
Try enabling Cache API call results in the settings, that should help somewhat.
