### ISSUE TITLE
Increase memory limit

### ISSUE THREAD

**Issue by Jalle19** [Jalle19/xbmc-video-server#231]
Users with very large libraries will reach the default 128 MB memory limit.

**Comment by Galixte** [comment]
Hi @Jalle19,

apart from the fact ask unlock the memory limit used by PHP, what is your recommendation ?

**Comment by Jalle19** [comment]
Recommendation about what? The memory limit?

**Comment by Galixte** [comment]
The method for users

**Comment by Jalle19** [comment]
There won't be a method, the limit can be changed directly from the code without the user having to do anything.

**Comment by Galixte** [comment]
ok, thanks.

**Comment by peu7510** [comment]
The solution is, you go to xampp directory to php directory and search php.ini and search the line memory limit and change 128M to 512 or 1024M

Well if you have a large library i recommend increase max execution timefor 30 to 60 seconds or 120 seconds
