### ISSUE TITLE
Problems with thumbnails

### ISSUE THREAD

**Issue by fbartels** [Jalle19/xbmc-video-server#251]
Hi Sam,

I recently had to reinstall xbmc-video-server since I messed up my local git checkout trying to make automated updates. Ever since then thumbnails (for videos, actors, ..) do not get displayed anymore.

I took a deeper look into my Apache logging (I also have a reverse proxy configured for /vfs just as described in the wiki) and found the following:

1. for some media there should be a placeholder image
But for some reason the path is a bit off. He tries to access ```http://myhostname/images/placeholder-video.jpg```, but the file is acutally located in ```http://myhostname/xbmc-video-server/src/images/placeholder-video.jpg``` (I as able to fix this by adding the full path in ```src/protected/models/thumbnail/ThumbnailFactory.php```, but this is not really an universal solution.

2. wrong path to vfs
In the log I also see calls to ```/vfs-statler/e/image%3a%2f%2fnfs%253a%252f%252fpath-to-image.jpg%2f``` that result in a 404. These acutally should be ```/vfs-statler/image%3a%2f%2fnfs%253a%252f%252fpath-to-image.jpg%2f``` (so without the additional e/ after vfs-statler/). I have set /vfs-statler as my proxy location for this backend.

Do you have any advice on how to fix these paths?

PS: streaming itself works fine

**Comment by Jalle19** [comment]
Did this use to work in a previous version? Can you also describe your reverse proxy setup in detail (post the Apache configuration for example)?

The placeholder thing is definitely a bug I managed to sneak in while doing some refactoring (the current code only works if the application is directly under the Apache web root). I'll post a fix for that.

**Comment by Jalle19** [comment]
Sorry for the hickup, pull the latest version using `git pull` (no need for the other upgrade commands for this one) and everything should work again!

**Comment by fbartels** [comment]
Thanks for the fast fix.
