### ISSUE TITLE
Possible to use it with Nginx?

### ISSUE THREAD

**Issue by bjoerns1983** [Jalle19/xbmc-video-server#261]
Hi there,
are there maybe some configuration suggestions to uns xbmc-video-server with nginx instead of Apache?
Maybe somebody already runs it in that combo?

**Comment by Jalle19** [comment]
I haven't tried it but naturally it should work. I've mainly stuck with Apache to be able to support Windows users since AFAIK nginx is not available on Windows.

**Comment by bjoerns1983** [comment]
Hmm okay, than i just have to figure it out how the site config for xbmc-video-server has to look lile, because nginx does not support .htaccess. So everything which is in there has to be "translated" to the nginx site config.

**Comment by Jalle19** [comment]
There aren't that many rules, the most important part is the URL rewriting.
