### ISSUE TITLE
Add support for optional LDAP authentication

### ISSUE THREAD

**Issue by mrskug** [Jalle19/xbmc-video-server#275]
see title....

**Comment by fbartels** [comment]
Hi, in the past I tried looking into external user auth for xbmc-video-server as well, but did not really make any progress on this topic. Instead if implementing a native ldap auth I would welcome a more universal approach. A good example which also lists benefits can be found at Kanboard http://kanboard.net/documentation/reverse-proxy-authentication

**Comment by Jalle19** [comment]
Closing, no bandwidth to fix this
