### ISSUE TITLE
Library refresh

### ISSUE THREAD

**Issue by cesko446** [Jalle19/xbmc-video-server#278]
Hi there, 
If i delete some files they're still on my library? Is it possibile to cleanup library?

**Comment by sigboe** [comment]
Try to run the library cleanup function in Kodi's setting menu

**Comment by Jalle19** [comment]
Perhaps you having caching enabled? If so you need to flush the cache manually from the Actions menu.

**Comment by Jalle19** [comment]
Either that or what @sigboe said, in which case the issue is unrelated to this application.

**Comment by cesko446** [comment]
I tried with flush function successfully. But i see sometimes clone entries I mean one single movie file is shown as 2 or 3 playbills. Strange...

**Comment by Jalle19** [comment]
You'll have to fix your library in Kodi, this application just mirrors what is shown there. Usually it's a weirdly named samplr or some extra material that is giving you duplicate entries.
