### ISSUE TITLE
fully offline functionality 

### ISSUE THREAD

**Issue by JackTheRipper79** [Jalle19/xbmc-video-server#283]
Hi

1st off I wish to thank you to super module I am in your debt.

I wish to run this on a environment with no internet on both the server and on the client side, 

with the current implementation it seems there some online access required to be able to use module.

is there way to host these requests on the webserver internally?
![snap1](https://user-images.githubusercontent.com/23498157/37511950-4f357c92-2909-11e8-9e9b-e02566ca9ee4.jpeg)

https://fonts.googleapis.com/css?family=Lato:400,700,900,400italic
https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js
https://fonts.gstatic.com/s/lato/v14/S6uyw4BMUTPHjx4wXiWtFCc.woff2
https://fonts.gstatic.com/s/lato/v14/S6u9w4BMUTPHh6UVSwiPGQ3q5d0.woff2

This should speedup the whole site dramatically if these request was hosted inside the module.
PS. - Assume I look at this with only border line insight into this development, and if there is a quick fix, i again can only thank you for your time and effort.

Regards
Jack

**Comment by Jalle19** [comment]
I have to check where we actually include the Google fonts, I think you're not allowed to redistribute them so in that case they would have to be replaced.

**Comment by Jalle19** [comment]
Turns out Google fonts can be distributed as long as the license is there so this wasn't that hard to change

**Comment by Jalle19** [comment]
@JackTheRipper79 update the latest release (see the wiki for details), should be fixed. If you find any other external requests let me know, but I think these were all of them.

**Comment by JackTheRipper79** [comment]
Thank you so much, for you fast response and tweaks, wishing you a awesome weekend.
