### ISSUE TITLE
Stream Movies over a XML Source

### ISSUE THREAD

**Issue by EscobarTeamCloud** [Jalle19/xbmc-video-server#286]
So my idea is, there‘s a addon called LastShip for Kodi where u can Watch Movies and Series.
You click  or search for your desired Movie and then it collects all Sources and check them for uptime and Quality and sort them from good to bad. The Source is opensource and i was wondering if its possible to integrate something like this.

My other question would be , for a more clean and faster flow and because i wanna expand my experience with Angular i would like to try to recode this if your cool with it (credits to you ofc) and i could possibly share or make it opensource if support is there.

**Comment by Jalle19** [comment]
> So my idea is, there‘s a addon called LastShip for Kodi where u can Watch Movies and Series.
> You click or search for your desired Movie and then it collects all Sources and check them for uptime and Quality and sort them from good to bad. The Source is opensource and i was wondering if its possible to integrate something like this.

I don't think this is possible. XBMC Video Server integrates with the Kodi library, so if you can get your items to show up in the library then it should work, but other than that it would be quite difficult.

> My other question would be , for a more clean and faster flow and because i wanna expand my experience with Angular i would like to try to recode this if your cool with it (credits to you ofc) and i could possibly share or make it opensource if support is there.

It's open source so you're free to hack on it as much as you'd like. However, the application is server side rendered so swapping out the UI for something else will require a lot of changes.

**Comment by Jalle19** [comment]
I'm closing this issue since there's not much I can do about it.
