### ISSUE TITLE
Raspberry pi installation instructions

### ISSUE THREAD

**Issue by amilino** [Jalle19/xbmc-video-server#293]
Hi, how to install it on Raspbian Stretch? Can someone please provide detailed steps?

**Comment by Jalle19** [comment]
The instructions should be nearly identical to the ones for Debian and Ubuntu. Try following those and re-open this issue if something doesn't work.

**Comment by amilino** [comment]
I already tried to follow this Ubuntu 14.04 and Debian Jessie. Most of packages are not available on Raspbian Stretch: libapache2-mod-php5 php5-imagick php5-cli php5-sqlite php5-json.

**Comment by amilino** [comment]
Also I am using php 7.0, does it mean I can replace 5 with 7.0? Will web application work?

By the way, I cannot re-open issue closed by you.

**Comment by Jalle19** [comment]
Yes, it works with PHP 7 too. Try replacing the package names, the rest should be fairly identical.

**Comment by amilino** [comment]
It works! Tnx.
