### ISSUE TITLE
Other libraries

### ISSUE THREAD

**Issue by amilino** [Jalle19/xbmc-video-server#294]
Would be cool to have Music library, Music videos and PVR.

**Comment by Galixte** [comment]
Hi @Jalle19,

could you take a look, please?

**Comment by Jalle19** [comment]
This is unfortunately way too much work so it won't get implemented. There are better solutions for music streaming, and last time I checked the JSON-RPC API for PVR features was somewhat lacking.

**Comment by amilino** [comment]
Maybe streaming is not that important, but would be cool to have a pure list to share with friends.
