### ISSUE TITLE
Recently added movies - show more items

### ISSUE THREAD

**Issue by amilino** [Jalle19/xbmc-video-server#296]
Is it possible to increase number of items displayed on Recently added movies page? I think number 24 is way too small number. Ideally would be to show all with paging.

**Comment by Galixte** [comment]
Hi @amilino,

I think it’s a kody setting, create a ```advancedsettings.xml``` file, in Windows it’s here: ```%appdata%\Kodi\userdata\``` (for other OS see here: https://kodi.wiki/view/Userdata), and put this setting inside:

```
<advancedsettings>
<videolibrary>
<recentlyaddeditems>60</recentlyaddeditems>
</videolibrary>
</advancedsettings>
```

Source: https://kodi.wiki/view/Advancedsettings.xml#videolibrary

**Comment by Jalle19** [comment]
It would maybe be possible to use GetMovies with a different sort instead of using GetRecentlyAddedMovies, but then again the whole view becomes slightly pointless. Maybe a better idea would be to check if the main movie list could optionally be sorted by date added.

**Comment by amilino** [comment]
Advanced settings has nothing to do to what is in code.

I agree that it shoud just be a GetMovies call with a different sorting.

**Comment by Jalle19** [comment]
You can sort the Movies page by date added now, that'll have to suffice :) I tried adjusting the number of items returned from GetRecentlyAddedMovies but Kodi limits these to 26 or something, which I guess is why 24 is the default, not 60 which is the default page size.

**Comment by amilino** [comment]
Yes that is also fine, but for Recently added movies page I removed parameter for records limit in code and increased to 60 in advanced config file for Kodi. Now I see 60 records. Thank you for all good work.

**Comment by amilino** [comment]
One small bug. Recently added movies are now sorted alphabetically when I enter the page.
