### ISSUE TITLE
For translations

### ISSUE THREAD

**Issue by Galixte** [Jalle19/xbmc-video-server#306]
Hi @Jalle19,

is there any language strings to translate since the last changes? Maybe there are since my FRENCH translated was updated 3 years ago, : https://github.com/Jalle19/xbmc-video-server/tree/master/src/protected/messages.

I don’t remember where are the English language keys to compare.

**Comment by Jalle19** [comment]
There's one or two for sure

**Comment by Jalle19** [comment]
@Galixte I updated the translation files, there are a couple of empty strings in de/fr now. If you want to feel free to translate them.

**Comment by Galixte** [comment]
https://github.com/Jalle19/xbmc-video-server/pull/310 & https://github.com/Jalle19/xbmc-video-server/pull/311.
