### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by amilino** [Jalle19/xbmc-video-server#316]
Anyone willing to create a dark theme css? 🙂

**Comment by Jalle19** [comment]
I'm really not that well versed in CSS these days so I'm going to have to pass on this one.

**Comment by Jalle19** [comment]
I had a quick look to see if it would be possible to just slap on a new dark-looking theme from Bootswatch (https://bootswatch.com/), but most of the dark themes are only available for Bootstrap 4.x (this project uses 2.3.x). It would be a huge undertaking to switch from LESS to SCSS so I doubt this will happen any time soon.

**Comment by alanmilinovic** [comment]
Hi, sorry for commenting on an old topic but there are some dark themes for Bootstrap 2.3.2.

https://bootswatch.com/2/

Like Cyborg or Slate.

**Comment by alanmilinovic** [comment]
I saw that you are active again on this project so wanted to ask if there is any hope for this topic? 😀

**Comment by alanmilinovic** [comment]
> I wouldn't exactly call it "active", and I at least personally don't have time or interest to implement a dark theme

It doesn't look that much work as dark theme already exist on Bootswatch, but yea if you don't have time it is fine. Thank you for reply though.
