### ISSUE TITLE
Please provide Dockerfile for mysql installation

### ISSUE THREAD

**Issue by niko2** [Jalle19/xbmc-video-server#320]
Using mysql seems to be possible, but needs some code to be modified.
Would it be possible to use mysql without code update ?
I can try to do a PR if you mind.

**Comment by Jalle19** [comment]
It's not officially supported but it shoulf work. Why do you want to use it, if I may ask?

**Comment by niko2** [comment]
1. I am already using mysql for kodi.
2. I want to limit (at least control) local I/Os.
3. I can easily access the SQL data (from another tool) if I want to

**Comment by Jalle19** [comment]
So basically you want to be able to use MySQL without having to edit this file: https://github.com/Jalle19/xbmc-video-server/blob/master/src/protected/config/_db.php ?

**Comment by Jalle19** [comment]
Could you test https://github.com/Jalle19/xbmc-video-server/pull/323 ? I've only verified that SQLite still works with this change, haven't actually tested with MySQL.
