### ISSUE TITLE
Docker volumes cannot be declared (as persistent) outside of the container

### ISSUE THREAD

**Issue by niko2** [Jalle19/xbmc-video-server#321]
I am using docker-compose and need to use persistent volumes (since I am using watchtower to update my containers and don't want to lose my config after an update !)
The volumes declared in Dockerfile (protected/data, protected/runtime, src/images) belong to the project and contains some important files, so they cannot be used as persistent ones.
A workaround could be to start and configure with existing volumes, then stop container, then copy their content to some persistent volumes, then restart container with these new volumes, etc. which is ugly and fastidious !

So I guess, some (little) work should be done to enable some volumes (empty and "write only") that could be defined persistent if user wants to.

**Comment by Jalle19** [comment]
I'm not really sure what the issue is here?

**Comment by niko2** [comment]
I fully agree ! It is not clear.

I would like to create empty volumes where the container will store the data it needs to keep to be able to start again when it is stopped/removed.

Not sure it is much more clear....

**Comment by Jalle19** [comment]
I changed the Dockerfile somewhat in https://github.com/Jalle19/xbmc-video-server/pull/322 to allow for easy setup as a self-contained systemd service. I'm not sure if the new approach helps you in any way, but at least now everything that should be persisted lives under the `/shared` volume inside the container.

**Comment by Jalle19** [comment]
Reading this again, the new Dockerfile should definitely easy your problems. Just map a directory as `/shared` inside the container and off you go. The entry point script will populate the directory with the initial database etc. if it's empty when you start the container, so you shouldn't need to run any special commands to get things up and running.

Let me know if you need more help!
