### ISSUE TITLE
no Thumbnails on RPi4 Buster

### ISSUE THREAD

**Issue by amilino** [Jalle19/xbmc-video-server#324]
Hi, I finally got Kodi running on my new RPi4 with Buster. What is strange is that now I don't have any pictures on any page, not even actor thumbnails. Do you have any idea what could be wrong? I followed this post to install Kodi `https://www.raspberrypi.org/forums/viewtopic.php?f=38&t=246837&p=1507311#p1507311`.

**Comment by Jalle19** [comment]
Probably a file permission issue. Anything in the application's system log?

**Comment by amilino** [comment]
yes:
`	
Imagine\Exception\RuntimeException: Gd not installed in /var/www/html/xbmc-video-server/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php:172

Stack trace:

#0 /var/www/html/xbmc-video-server/vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php(39): Imagine\Gd\Imagine->loadGdInfo()

#1 /var/www/html/xbmc-video-server/src/protected/models/thumbnail/Thumbnail.php(164): Imagine\Gd\Imagine->__construct()

#2 /var/www/html/xbmc-video-server/src/protected/models/thumbnail/Thumbnail.php(117): Thumbnail::imagineFactory()

#3 /var/www/html/xbmc-video-server/src/protected/controllers/ThumbnailController.php(36): Thumbnail->generate()

#4 [internal function]: ThumbnailController->actionGenerate('image://http%3a...', '160')

#5 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(ThumbnailController), Array)

#6 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(ThumbnailController), Object(ReflectionMethod), Array)

#7 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)

#8 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))

#9 /var/www/html/xbmc-video-server/src/protected/controllers/base/Controller.php(65): CFilterChain->run()

#10 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): Controller->filterReleaseSessionLock(Object(CFilterChain))

#11 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))

#12 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()

#13 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)

#14 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('generate')

#15 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('thumbnail/gener...')

#16 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()

#17 /var/www/html/xbmc-video-server/src/index.php(26): CApplication->run()

#18 {main}

REQUEST_URI=/xbmc-video-server/src/thumbnail/generate?path=image%3A%2F%2Fhttp%253a%252f%252fimage.tmdb.org%252ft%252fp%252foriginal%252fweAvkxl0dnPevIKD8fwHjiOi6tc.jpg%2F&size=160

HTTP_REFERER=http://1raspberrypi.mooo.com:20080/xbmc-video-server/src/movie/recentlyAdded
`

**Comment by amilino** [comment]
Ok I had to install `sudo apt-get install php7.2-gd` followed by `sudo service apache2 restart`.

**Comment by amilino** [comment]
It looks like php imagick mod is not needed, instead I used gd mod.
