### ISSUE TITLE
Error in tv shows detail page

### ISSUE THREAD

**Issue by amilino** [Jalle19/xbmc-video-server#325]
When I open any tv show detail page I can see following error in log:

Details for log item #921
Level	error
Category	exception.CHttpException.500
Logtime	2019-07-28 18:59:08
Source address	88.152.40.156
Message	
CHttpException: Exception caught while calling XBMC API: Invalid params. (-32602) in /var/www/html/xbmc-video-server/src/protected/components/XBMC.php:171

Stack trace:

#0 /var/www/html/xbmc-video-server/src/protected/components/XBMC.php(111): XBMC->handleRequestException(Object(SimpleJsonRpcClient\Exception\InvalidParamsException), Object(SimpleJsonRpcClient\Request\Request))

#1 /var/www/html/xbmc-video-server/src/protected/components/XBMC.php(77): XBMC->performRequestUncached('Files.PrepareDo...', Array, 0)

#2 /var/www/html/xbmc-video-server/src/protected/models/thumbnail/Thumbnail.php(89): XBMC->performRequest('Files.PrepareDo...', Array)

#3 /var/www/html/xbmc-video-server/src/protected/models/thumbnail/Thumbnail.php(110): Thumbnail->getOriginalUrl()

#4 /var/www/html/xbmc-video-server/src/protected/controllers/ThumbnailController.php(36): Thumbnail->generate()

#5 [internal function]: ThumbnailController->actionGenerate('image://http%3a...', '160')

#6 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(ThumbnailController), Array)

#7 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(ThumbnailController), Object(ReflectionMethod), Array)

#8 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)

#9 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(134): CController->runAction(Object(CInlineAction))

#10 /var/www/html/xbmc-video-server/src/protected/controllers/base/Controller.php(65): CFilterChain->run()

#11 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): Controller->filterReleaseSessionLock(Object(CFilterChain))

#12 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))

#13 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()

#14 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)

#15 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('generate')

#16 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('thumbnail/gener...')

#17 /var/www/html/xbmc-video-server/vendor/yiisoft/yii/framework/base/CApplication.php(185): CWebApplication->processRequest()

#18 /var/www/html/xbmc-video-server/src/index.php(26): CApplication->run()

#19 {main}

REQUEST_URI=/xbmc-video-server/src/thumbnail/generate?path=image%3A%2F%2Fhttp%253a%252f%252fimage.tmdb.org%252ft%252fp%252foriginal%252fqlEznv2uAbN46pmVaAuWNTULdVh.jpg%2F&size=160

HTTP_REFERER=http://1raspberrypi.mooo.com:20080/xbmc-video-server/src/tvShow/details/213

---

**Comment by Jalle19** [comment]
This tends to happen when an image request fails. I haven't been able to figure it out, for me it only happens with older library items. Could be that the file is missing in Kodi.

I wouldn't worry too much about this one.
