### ISSUE TITLE
Missing movie thumbnails on Kodi Matrix

### ISSUE THREAD

**Issue by alanmilinovic** [Jalle19/xbmc-video-server#329]
After upgrading Kodi to 19.3 and php to 7.4 all thumbnails for movies are not displaying. TV shows have no issues and all looks just fine though. There are no errors in the log section.

Any suggestion what could be wrong?

Could be again issue with php7.4-gd package, like I had in the past?

**Comment by Jalle19** [comment]
Double-check that you have php7.4-gd installed and enabled

**Comment by alanmilinovic** [comment]
Yes it is installed and enabled.

`php7.4-gd:
  Installed: 7.4.25-1+deb11u1
  Candidate: 7.4.25-1+deb11u1
  Version table:
 *** 7.4.25-1+deb11u1 500
        500 http://security.debian.org/debian-security bullseye-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.4.21-1+deb11u1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages`

`$ php -m | grep "gd"
gd`

**Comment by Jalle19** [comment]
Do you see any error entres (red) in the applicaton's system log?

**Comment by alanmilinovic** [comment]
No, all clean.

**Comment by Jalle19** [comment]
If you press F12 in your browser to open the developer tools, then look at the Network tab while you refresh a page that should have thumbnails on it, do you see any HTTP 400/404/500 responses for images?

**Comment by Jalle19** [comment]
Can you also try refreshing the art for one movie in Kodi, and see if that movie's image starts working? I have some older movies in my library that have corrupted images in XBMC Video Server, and the only way I've been able to fix them is by refreshing the artwork.

**Comment by alanmilinovic** [comment]
I don't see any errors for images except for the fonts and favicon.ico.
`styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-regular.woff2 net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-900.woff2 net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-regular.woff net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-900.woff net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-italic.woff2 net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-italic.woff net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-700.woff2 net::ERR_ABORTED 404 (Not Found)
styles-min.css:1 GET http://192.168.188.203:20530/fonts/lato/lato-v14-latin-700.woff net::ERR_ABORTED 404 (Not Found)
favicon.ico:1 GET http://192.168.188.203:20530/favicon.ico 404 (Not Found)`

placeholder-video.jpg is showing 200 of course.

Tried to refresh one movie and same thing. Interesting is that I can see images for the actors.

**Comment by Jalle19** [comment]
Okay, so you're seeing a bunch of placeholder images for movies, not the tiny icon your browser uses to indicate that it couldn't load the image? Can you share a screenshot here?

**Comment by Jalle19** [comment]
I'm personally still on Kodi 18.x so I can't check if this is a general issue or something that's only affecting you

**Comment by alanmilinovic** [comment]
> Okay, so you're seeing a bunch of placeholder images for movies, not the tiny icon your browser uses to indicate that it couldn't load the image? Can you share a screenshot here?

Exactly, here is the screenshot.
![image](https://user-images.githubusercontent.com/1752983/144849651-11d726e8-ad91-49a2-8844-7d47bb596c6b.png)

**Comment by alanmilinovic** [comment]
Other programs I am using to connect to Kodi like Yatse or even Kodi UI (Chorus) looks fine.

**Comment by Jalle19** [comment]
Perhaps something has changed in Kodi's JSON-RPC API. I'll have to spin up a test instance with Kodi 19 and get back to you.

**Comment by alanmilinovic** [comment]
That would be awesome, tnx.

**Comment by alanmilinovic** [comment]
Any news, were you able to reproduce the bug?

**Comment by Jalle19** [comment]
Sorry, I haven't gotten around to testing with Kodi 19 yet.

**Comment by alanmilinovic** [comment]
Sorry for asking over and over but did you had any chance to check maybe? Can I somehow help you?

**Comment by Jalle19** [comment]
Sorry, I haven't yet upgraded to Matrix personally 😅

**Comment by Jalle19** [comment]
Finally got around to upgrading to Kodi 19 so now I have a change to fix this

**Comment by alanmilinovic** [comment]
Cool, looking forward to it.

**Comment by alanmilinovic** [comment]
Any news?

**Comment by alanmilinovic** [comment]
Hi, I think there are some changes in database that's why thumbnails are not showned anylonger since version 19. Tried to check the code but I don't have envitonment for yii where I can test it.

**Comment by Jalle19** [comment]
Fixed in version 1.10.4, sorry that it took forever! See https://github.com/Jalle19/xbmc-video-server/wiki/Installation-instructions for how to update

**Comment by alanmilinovic** [comment]
Wow, many tnx man!
