### ISSUE TITLE
Add support for running on PHP 8.x

### ISSUE THREAD

**Issue by alanmilinovic** [Jalle19/xbmc-video-server#334]
When running `sudo php ./src/protected/yiic.php migrate --interactive=0` I get this error:
`PHP Fatal error:  The (unset) cast is no longer supported in /var/www/html/xbmc-video-server/vendor/hoa/core/Core.php on line 146`

I am on PHP 8.2.7.

**Comment by Jalle19** [comment]
It seems like we have to replace the WebSocket library we're currently using

**Comment by alanmilinovic** [comment]
> It seems like we have to replace the WebSocket library we're currently using

Hm, is it a big change?

**Comment by Jalle19** [comment]
Shouldn't be that big, it's only used for library updates

**Comment by alanmilinovic** [comment]
Ok, thanks for the info. I will be waiting for the new commit and can perform some testing if needed.

**Comment by Jalle19** [comment]
More issues:
> PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /vagrant/vendor/netresearch/jsonmapper/src/JsonMapper.php on line 219, referer: http://10.110.3.31/setting/admin

**Comment by Jalle19** [comment]
https://github.com/hoaproject/Http/issues/32

**Comment by Jalle19** [comment]
Closed by https://github.com/Jalle19/xbmc-video-server/pull/336
